#!/bin/bash
echo "/root/multi.sh" > /bin/mko && chmod +x /bin/mko > /dev/null 2>&1

spw () {
      apt install dos2unix -y; wget https://raw.githubusercontent.com/wellzin-blip/v2022/master/gestorssh/sincpainel && chmod +x sincpainel && dos2unix sincpainel && ./sincpainel
}
while true $x != "ok"
do
clear
echo -e "\033[0;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[44;1;37m    RAFS NET 4G SSH V3 FERRAMENTAS            \E[0m"
echo -e "\033[0;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;31m  [\033[1;36m 01 \033[1;31m] \033[1;37m• \033[1;37mSINCRO PAINEIS WEB SSH"
echo -e "\033[1;31m  [\033[1;36m 02 \033[1;31m] \033[1;37m• \033[1;37mCHECKUSER 4G $chk"
echo -e "\033[1;31m  [\033[1;36m 03 \033[1;31m] \033[1;37m• \033[1;37mCHECKUSER GL"
echo -e "\033[1;31m  [\033[1;36m 04 \033[1;31m] \033[1;37m• \033[1;37mBOT VENDAS"
echo -e "\033[1;31m  [\033[1;36m 05 \033[1;31m] \033[1;37m• \033[1;37mEM BREVE"
echo -e "\033[1;31m  [\033[1;36m 00 \033[1;31m] \033[1;37m• \033[1;37mVOLTAR AO MENU"
echo -e "\033[0;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -ne "\033[1;32m O QUE DESEJA FAZER \033[1;37m?\033[1;31m?\033[1;37m : "; read x

case "$x" in 
   1 | 01)
   clear
   spw
   ;;
    2 | 02)
   clear
   initcheck
   ;;  
    3 | 03)
   clear
   bash <(curl -sL https://raw.githubusercontent.com/DuTra01/CheckUser/master/install.sh)
   ;;  
    4 | 04)
   rm -rf BOT > /dev/null 2>&1 && bash <(wget -qO- https://raw.githubusercontent.com/rafsnet4g/RafsSSHv3/main/instalador/botteste)
   ;;  
    5 | 05)
   onapp_ssh
   ;;  
    0 | 00)
   clear
   menu
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
done
}
#fim
